/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"amount": "amount",
		"cashlessEmail": "cashlessEmail",
		"cashlessMode": "cashlessMode",
		"cashlessOTP": "cashlessOTP",
		"cashlessOTPValidDate": "cashlessOTPValidDate",
		"cashlessPersonName": "cashlessPersonName",
		"cashlessPhone": "cashlessPhone",
		"cashlessSecurityCode": "cashlessSecurityCode",
		"cashWithdrawalTransactionStatus": "cashWithdrawalTransactionStatus",
		"category": "category",
		"description": "description",
		"ExternalAccountNumber": "ExternalAccountNumber",
		"frequencyEndDate": "frequencyEndDate",
		"frequencyStartDate": "frequencyStartDate",
		"frequencyType": "frequencyType",
		"fromAccountBalance": "fromAccountBalance",
		"fromAccountName": "fromAccountName",
		"fromAccountNumber": "fromAccountNumber",
		"fromAccountType": "fromAccountType",
		"fromNickName": "fromNickName",
		"hasDepositImage": "hasDepositImage",
		"isScheduled": "isScheduled",
		"numberOfRecurrences": "numberOfRecurrences",
		"payeeId": "payeeId",
		"payeeNickName": "payeeNickName",
		"payeeAddressLine1": "payeeAddressLine1",
		"payeeAddressLine2": "payeeAddressLine2",
		"payPersonEmail": "payPersonEmail",
		"payPersonName": "payPersonName",
		"payPersonPhone": "payPersonPhone",
		"recurrenceDesc": "recurrenceDesc",
		"scheduledDate": "scheduledDate",
		"statusDescription": "statusDescription",
		"toAccountName": "toAccountName",
		"toAccountNumber": "toAccountNumber",
		"toAccountType": "toAccountType",
		"transactionComments": "transactionComments",
		"transactionDate": "transactionDate",
		"transactionId": "transactionId",
		"transactionsNotes": "transactionsNotes",
		"transactionType": "transactionType",
		"viewReportLink": "viewReportLink",
		"IBAN": "IBAN",
		"sortCode": "sortCode",
		"feeCurrency": "feeCurrency",
		"fee": "fee",
		"feePaidByReceipent": "feePaidByReceipent",
		"convertedAmount": "convertedAmount",
		"transactionCurrency": "transactionCurrency",
		"baseCurrency": "baseCurrency",
		"isInternationalAccount": "isInternationalAccount",
		"swiftCode": "swiftCode",
		"bankName": "bankName",
		"serviceName": "serviceName",
		"billerId": "billerId",
		"firstRecordNumber": "firstRecordNumber",
		"lastRecordNumber": "lastRecordNumber",
		"order": "order",
		"sortBy": "sortBy",
	};

	Object.freeze(mappings);

	var typings = {
		"amount": "string",
		"cashlessEmail": "string",
		"cashlessMode": "string",
		"cashlessOTP": "string",
		"cashlessOTPValidDate": "string",
		"cashlessPersonName": "string",
		"cashlessPhone": "string",
		"cashlessSecurityCode": "string",
		"cashWithdrawalTransactionStatus": "string",
		"category": "string",
		"description": "string",
		"ExternalAccountNumber": "string",
		"frequencyEndDate": "string",
		"frequencyStartDate": "string",
		"frequencyType": "string",
		"fromAccountBalance": "string",
		"fromAccountName": "string",
		"fromAccountNumber": "string",
		"fromAccountType": "string",
		"fromNickName": "string",
		"hasDepositImage": "string",
		"isScheduled": "string",
		"numberOfRecurrences": "string",
		"payeeId": "string",
		"payeeNickName": "string",
		"payeeAddressLine1": "string",
		"payeeAddressLine2": "string",
		"payPersonEmail": "string",
		"payPersonName": "string",
		"payPersonPhone": "string",
		"recurrenceDesc": "string",
		"scheduledDate": "string",
		"statusDescription": "string",
		"toAccountName": "string",
		"toAccountNumber": "string",
		"toAccountType": "string",
		"transactionComments": "string",
		"transactionDate": "string",
		"transactionId": "string",
		"transactionsNotes": "string",
		"transactionType": "string",
		"viewReportLink": "string",
		"IBAN": "string",
		"sortCode": "string",
		"feeCurrency": "string",
		"fee": "string",
		"feePaidByReceipent": "string",
		"convertedAmount": "string",
		"transactionCurrency": "string",
		"baseCurrency": "string",
		"isInternationalAccount": "string",
		"swiftCode": "string",
		"bankName": "string",
		"serviceName": "string",
		"billerId": "string",
		"firstRecordNumber": "string",
		"lastRecordNumber": "string",
		"order": "string",
		"sortBy": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"transactionId",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "Transfers",
		tableName: "UpcomingTransactions"
	};

	Object.freeze(config);

	return config;
})