/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"lastName": "lastName",
		"zipCode": "zipCode",
		"isAutoPayEnabled": "isAutoPayEnabled",
		"companyName": "companyName",
		"ebillSupport": "ebillSupport",
		"lastPaidAmount": "lastPaidAmount",
		"EBillEnable": "EBillEnable",
		"billermaster_id": "billermaster_id",
		"lastPaidDate": "lastPaidDate",
		"cityName": "cityName",
		"addressLine1": "addressLine1",
		"addressLine2": "addressLine2",
		"isManuallyAdded": "isManuallyAdded",
		"id": "id",
		"state": "state",
		"email": "email",
		"nameOnBill": "nameOnBill",
		"isWiredRecepient": "isWiredRecepient",
		"nickName": "nickName",
		"transitDays": "transitDays",
		"accountNumber": "accountNumber",
		"userId": "userId",
		"isBusinessPayee": "isBusinessPayee",
		"firstName": "firstName",
		"phone": "phone",
		"billid": "billid",
		"name": "name",
		"payeeId": "payeeId",
		"payeeName": "payeeName",
		"payeeNickName": "payeeNickName",
		"limit": "limit",
		"offset": "offset",
		"sortBy": "sortBy",
		"order": "order",
		"searchString": "searchString",
		"bankAddressLine1": "bankAddressLine1",
		"bankAddressLine2": "bankAddressLine2",
		"bankState": "bankState",
		"bankCity": "bankCity",
		"bankZip": "bankZip",
		"bankName": "bankName",
		"notes": "notes",
		"swiftCode": "swiftCode",
		"iban": "iban",
		"phoneCountryCode": "phoneCountryCode",
		"phoneExtension": "phoneExtension",
		"cif": "cif",
		"dbpErrMsg": "dbpErrMsg",
		"dbpErrCode": "dbpErrCode",
		"internationalRoutingCode": "internationalRoutingCode",
		"routingCode": "routingCode",
		"wireAccountType": "wireAccountType",
		"country": "country",
		"street": "street",
		"billDescription": "billDescription",
		"billDueDate": "billDueDate",
		"billerCategory": "billerCategory",
		"billerId": "billerId",
		"billGeneratedDate": "billGeneratedDate",
		"dueAmount": "dueAmount",
		"ebillURL": "ebillURL",
		"paidAmount": "paidAmount",
		"beneficiaryId": "beneficiaryId",
		"transactionId": "transactionId",
	};

	Object.freeze(mappings);

	var typings = {
		"lastName": "string",
		"zipCode": "string",
		"isAutoPayEnabled": "string",
		"companyName": "string",
		"ebillSupport": "string",
		"lastPaidAmount": "string",
		"EBillEnable": "string",
		"billermaster_id": "string",
		"lastPaidDate": "string",
		"cityName": "string",
		"addressLine1": "string",
		"addressLine2": "string",
		"isManuallyAdded": "string",
		"id": "string",
		"state": "string",
		"email": "string",
		"nameOnBill": "string",
		"isWiredRecepient": "string",
		"nickName": "string",
		"transitDays": "string",
		"accountNumber": "string",
		"userId": "string",
		"isBusinessPayee": "string",
		"firstName": "string",
		"phone": "string",
		"billid": "string",
		"name": "string",
		"payeeId": "string",
		"payeeName": "string",
		"payeeNickName": "string",
		"limit": "string",
		"offset": "string",
		"sortBy": "string",
		"order": "string",
		"searchString": "string",
		"bankAddressLine1": "string",
		"bankAddressLine2": "string",
		"bankState": "string",
		"bankCity": "string",
		"bankZip": "string",
		"bankName": "string",
		"notes": "string",
		"swiftCode": "string",
		"iban": "string",
		"phoneCountryCode": "string",
		"phoneExtension": "string",
		"cif": "string",
		"dbpErrMsg": "string",
		"dbpErrCode": "string",
		"internationalRoutingCode": "string",
		"routingCode": "string",
		"wireAccountType": "string",
		"country": "string",
		"street": "string",
		"billDescription": "string",
		"billDueDate": "string",
		"billerCategory": "string",
		"billerId": "string",
		"billGeneratedDate": "string",
		"dueAmount": "string",
		"ebillURL": "string",
		"paidAmount": "string",
		"beneficiaryId": "string",
		"transactionId": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"id",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "BillPay",
		tableName: "Payee_BillPay"
	};

	Object.freeze(config);

	return config;
})