/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"accountNumber": "accountNumber",
		"amount": "amount",
		"cashlessEmail": "cashlessEmail",
		"cashlessMode": "cashlessMode",
		"cashlessOTP": "cashlessOTP",
		"cashlessOTPValidDate": "cashlessOTPValidDate",
		"cashlessPersonName": "cashlessPersonName",
		"cashlessPhone": "cashlessPhone",
		"cashlessPin": "cashlessPin",
		"cashlessSecurityCode": "cashlessSecurityCode",
		"cashWithdrawalTransactionStatus": "cashWithdrawalTransactionStatus",
		"category": "category",
		"checkNumber": "checkNumber",
		"description": "description",
		"firstRecordNumber": "firstRecordNumber",
		"frequencyEndDate": "frequencyEndDate",
		"frequencyStartDate": "frequencyStartDate",
		"frequencyType": "frequencyType",
		"fromAccountBalance": "fromAccountBalance",
		"fromAccountName": "fromAccountName",
		"fromAccountNumber": "fromAccountNumber",
		"fromAccountType": "fromAccountType",
		"fromCheckNumber": "fromCheckNumber",
		"hasDepositImage": "hasDepositImage",
		"isScheduled": "isScheduled",
		"lastRecordNumber": "lastRecordNumber",
		"numberOfRecurrences": "numberOfRecurrences",
		"order": "order",
		"payeeNickName": "payeeNickName",
		"recurrenceDesc": "recurrenceDesc",
		"scheduledDate": "scheduledDate",
		"searchAmount": "searchAmount",
		"searchDateRange": "searchDateRange",
		"searchDescription": "searchDescription",
		"searchEndDate": "searchEndDate",
		"searchMaxAmount": "searchMaxAmount",
		"searchMinAmount": "searchMinAmount",
		"searchStartDate": "searchStartDate",
		"searchTransactionType": "searchTransactionType",
		"searchType": "searchType",
		"sortBy": "sortBy",
		"statusDescription": "statusDescription",
		"toAccountName": "toAccountName",
		"toAccountNumber": "toAccountNumber",
		"toAccountType": "toAccountType",
		"toCheckNumber": "toCheckNumber",
		"transactionComments": "transactionComments",
		"transactionDate": "transactionDate",
		"transactionId": "transactionId",
		"transactionType": "transactionType",
		"payeeCurrency": "payeeCurrency",
		"IBAN": "IBAN",
		"transactionCurrency": "transactionCurrency",
		"sortCode": "sortCode",
		"feeCurrency": "feeCurrency",
		"feePaidByReceipent": "feePaidByReceipent",
		"convertedAmount": "convertedAmount",
		"baseCurrency": "baseCurrency",
		"isInternationalAccount": "isInternationalAccount",
		"serviceName": "serviceName",
		"MoreRecordsToken": "MoreRecordsToken",
		"MoreRecordsflag": "MoreRecordsflag",
		"TransactionsMoreRecordsToken": "TransactionsMoreRecordsToken",
		"id": "id",
		"paidBy": "paidBy",
		"fileNames": "fileNames",
		"fileName": "fileName",
		"fileID": "fileID",
		"paymentStatus": "paymentStatus",
		"pendingApproval": "pendingApproval",
		"beneficaryName": "beneficaryName",
		"ExternalAccountNumber": "ExternalAccountNumber",
		"fromNickName": "fromNickName",
		"payeeId": "payeeId",
		"payPersonEmail": "payPersonEmail",
		"payPersonName": "payPersonName",
		"payPersonPhone": "payPersonPhone",
		"transactionsNotes": "transactionsNotes",
	};

	Object.freeze(mappings);

	var typings = {
		"accountNumber": "string",
		"amount": "string",
		"cashlessEmail": "string",
		"cashlessMode": "string",
		"cashlessOTP": "string",
		"cashlessOTPValidDate": "string",
		"cashlessPersonName": "string",
		"cashlessPhone": "string",
		"cashlessPin": "string",
		"cashlessSecurityCode": "string",
		"cashWithdrawalTransactionStatus": "string",
		"category": "string",
		"checkNumber": "string",
		"description": "string",
		"firstRecordNumber": "string",
		"frequencyEndDate": "string",
		"frequencyStartDate": "string",
		"frequencyType": "string",
		"fromAccountBalance": "string",
		"fromAccountName": "string",
		"fromAccountNumber": "string",
		"fromAccountType": "string",
		"fromCheckNumber": "string",
		"hasDepositImage": "string",
		"isScheduled": "string",
		"lastRecordNumber": "string",
		"numberOfRecurrences": "string",
		"order": "string",
		"payeeNickName": "string",
		"recurrenceDesc": "string",
		"scheduledDate": "string",
		"searchAmount": "string",
		"searchDateRange": "string",
		"searchDescription": "string",
		"searchEndDate": "string",
		"searchMaxAmount": "string",
		"searchMinAmount": "string",
		"searchStartDate": "string",
		"searchTransactionType": "string",
		"searchType": "string",
		"sortBy": "string",
		"statusDescription": "string",
		"toAccountName": "string",
		"toAccountNumber": "string",
		"toAccountType": "string",
		"toCheckNumber": "string",
		"transactionComments": "string",
		"transactionDate": "string",
		"transactionId": "string",
		"transactionType": "string",
		"payeeCurrency": "string",
		"IBAN": "string",
		"transactionCurrency": "string",
		"sortCode": "string",
		"feeCurrency": "string",
		"feePaidByReceipent": "string",
		"convertedAmount": "string",
		"baseCurrency": "string",
		"isInternationalAccount": "string",
		"serviceName": "string",
		"MoreRecordsToken": "string",
		"MoreRecordsflag": "string",
		"TransactionsMoreRecordsToken": "string",
		"id": "string",
		"paidBy": "string",
		"fileNames": "string",
		"fileName": "string",
		"fileID": "string",
		"paymentStatus": "string",
		"pendingApproval": "boolean",
		"beneficaryName": "string",
		"ExternalAccountNumber": "string",
		"fromNickName": "string",
		"payeeId": "string",
		"payPersonEmail": "string",
		"payPersonName": "string",
		"payPersonPhone": "string",
		"transactionsNotes": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"transactionId",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "Transfers",
		tableName: "StandingInstruction"
	};

	Object.freeze(config);

	return config;
})